### ISSUE TITLE
Add option to model the correlation of random intercepts between channels

### ISSUE THREAD

**Issue by helske** [santikka/dynamite#33]
If we assume that the random intercept corresponds to some latent "trait" of a group, then it is reasonable also to assume that these could be correlated.

This should be relatively simple to do if we define the common correlation in `stanblocks` instead of `stanblocks_families`, and add an argument `correlated_nu` to `dynamite`. Other option would be to define new function `random(channels = character(), correlated = logical(1))` similarly as `lags()` and `splines()` which would be used to add random intercept components instead of inside `obs`. This latter option would be perhaps more elegant and in line with the overall style of the package but I think it would make it more difficult to define priors etc.

**Comment by santikka** [comment]
I think a `dynamiteformula` should completely define the model. If the correlation is an argument to `dynamite` instead, this would no longer be the case.

**Comment by helske** [comment]
Good point. I also realised that this would break the `predict` method in terms of generating new random intercepts which cannot be done independently for each channel anymore.

**Comment by santikka** [comment]
I think this feature could be supported by first implementing multivariate channels, e.g., something like `obs(c(y1, y2) ~ ...,, family = c("gaussian", "exponential"))` which could also support multivariate distributions. A random intercept for such a channel would be correlated by default between the responses of the channel. This way channels would still be independent.

**Comment by helske** [comment]
That could an option as well. I now went with keeping the channels univariate but allowing separate random component, which I think I was able to code relatively cleanly (e.g., we can generate the intercepts in prediction before starting looping over the channels/time). I see that with your suggestion we could have correlated error terms for gaussian channels which could perhaps be useful.
