### ISSUE TITLE
Allow newdata in fitted?

### ISSUE THREAD

**Issue by helske** [santikka/dynamite#39]
Currently, `predict` will only simulate for the NA values in the data, or in the default case everything given the first fixed time points, whereas `fitted` computes new predictions given the fixed (original) data. But often you might want to compute "one-step-ahead" (in case of maximum lag of one) predictions under different scenarios for each time point (in case of time-varying coefficients). For example, in the categorical case it can be of interest to compute how the probability of transitioning from one category to other changes in time. This is currently not possible, as `fitted` does not accept `newdata` argument (except by repeated calls to `predict` with rolling NA pattern).

I think it would be good idea to allow newdata in `fitted` as well. So basically `fitted` and `predict` with `type="mean"` would be identical except that `fitted` always conditions on the original `newdata` whereas `predict` conditions on the simulated values of the previous time point(s).

**Comment by santikka** [comment]
Seems like a good idea, however this makes `fitted` and `predict` highly similar in terms of code so it may be smart to only have a single internal predict function with the exported methods as wrappers. Basically, the only difference would be which columns of the responses are used for simulation and to compute the lagged values.

**Comment by helske** [comment]
Yes, of course in `fitted` version it is enough to create the model matrix only once, although when I was testing the current `fitted` for categorical data it failed due to the lack of memory because the model matrix is expanded at the beginning, whereas `predict` works fine as the model matrix is constructed separately for each time point.

**Comment by santikka** [comment]
Not surprising considering how large the expanded model matrix might be with large `n_draws`, even more reason to just use the current `predict` code with some variation.

**Comment by helske** [comment]
`newdata` is now supported in `fitted` as per 33a042fbadb691a5e67e6b4087afffa1582862ab, seems to work but the code is pretty much a replication of `predict` so not ideal.

**Comment by santikka** [comment]
We can think about how to refactor later which shouldn't be too difficult.

**Comment by santikka** [comment]
Refactoring was completed in 54d9943.
