### ISSUE TITLE
Optimize code for performance

### ISSUE THREAD

**Issue by santikka** [santikka/dynamite#4]
I think there is some potential for performance improvements by rewriting the definitions of beta/a/likelihood, need to test and profile a bit.

This talk gives some potentially useful info on how autodiff etc works in stan:
There are some speed comparisons here: https://www.youtube.com/watch?v=EJLXoDBoVko

I wonder if it would be beneficial to write our own likelihood functions based on spline coefficients directly with analytical gradients. Lots of work though, and no guarantees it helps...

**Comment by helske** [comment]
I think the Stan code performance is pretty much optimal if we ignore rewriting gradients etc which is bit of a stretch. At some point we could consider within-chain parallelization, but I'll close this issue for now.
