### ISSUE TITLE
Allow group-specific values of `past` in `aux`

### ISSUE THREAD

**Issue by helske** [santikka/dynamite#44]
So something like this:

```
obs(y ~ lag(x)) + aux(x ~ lag(x) + log(y) + past(z))
```
Probably the best option is  to look for `z` is in the `data` and use the first values for each group. This keeps all the data used in the modelling in the same place. Small imperfection is that the rest of the `z` are ignored but are needlessly kept around. On the other hand, it makes it natural to use something like `past(log(y))` in the example above. Another option would be to add an additional `aux_data` argument to `dynamite`.

**Comment by santikka** [comment]
After the past values have been assigned, there is no need to keep the entire column in the data if it is not otherwise used. In fact, this should be done anyway to conserve memory. I will add a separate issue on this.
