### ISSUE TITLE
Disallow the use of the 'as-is' function I(.) in formulas

### ISSUE THREAD

**Issue by santikka** [santikka/dynamite#9]
I think we should disable the as-is function for the following reasons:

1. Formula syntax would be more robust, i.e., no new variables are generated on the fly that we are not in control of.
2. Users would be encouraged to use deterministic channels for transformations, so that their predictions will also work.
3. Transformations of fixed predictors that are independent of the responses can be done beforehand anyway.

**Comment by helske** [comment]
Totally agree.

**Comment by santikka** [comment]
Actually resolved by 6357dcee24ae34880d6846caaa2ddc60c9bd4ce4
